MATCH_KIND_LEFTMOST_FIRST: int
MATCH_KIND_LEFTMOST_LONGEST: int
MATCH_KIND_STANDARD: int

class DoubleArrayAhoCorasick:
    def __init__(self, patterns: list[bytes], match_kind: int = 0) -> None: ...
    def find(self, haystack: bytes) -> list[tuple[int, int, int]]: ...
    def find_overlapping(self, haystack: bytes) -> list[tuple[int, int, int]]: ...
    def find_overlapping_no_suffix(self, haystack: bytes) -> list[tuple[int, int, int]]: ...
    def serialize(self) -> bytes: ...
    @staticmethod
    def deserialize(data: bytes) -> "DoubleArrayAhoCorasick": ...

class CharwiseDoubleArrayAhoCorasick:
    def __init__(self, patterns: list[str], match_kind: int = 0) -> None: ...
    def find(self, haystack: str) -> list[tuple[int, int, int]]: ...
    def find_overlapping(self, haystack: str) -> list[tuple[int, int, int]]: ...
    def find_overlapping_no_suffix(self, haystack: str) -> list[tuple[int, int, int]]: ...
    def serialize(self) -> bytes: ...
    @staticmethod
    def deserialize(data: bytes) -> "CharwiseDoubleArrayAhoCorasick": ...
