name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  sdist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - name: Build package
      uses: PyO3/maturin-action@v1
      with:
        command: sdist
    - name: Upload wheels
      uses: actions/upload-artifact@v7
      with:
        name: wheels-sdist
        path: target/wheels

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14' ]
        target: [ x86_64, x86 ]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build package
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ matrix.target }}
        manylinux: auto
        args: -i ${{ matrix.python-version }} --release
    - name: Test package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install daachorse --no-index --find-links target/wheels --force-reinstall
        mypy --strict tests
        pytest
    - name: Upload wheels
      uses: actions/upload-artifact@v7
      with:
        name: wheels-linux-${{ matrix.python-version }}-${{ matrix.target }}
        path: target/wheels

  musllinux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14' ]
        target: [ x86_64, x86 ]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build package
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ matrix.target }}
        manylinux: musllinux_1_2
        args: -i ${{ matrix.python-version }} --release
    - name: Test package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install daachorse --no-index --find-links target/wheels --force-reinstall
        mypy --strict tests
        pytest
    - name: Upload wheels
      uses: actions/upload-artifact@v7
      with:
        name: wheels-musllinux-${{ matrix.python-version }}-${{ matrix.target }}
        path: target/wheels

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14' ]
        target: [ x64, x86 ]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.target }}
    - name: Build package
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ matrix.target }}
        args: -i ${{ matrix.python-version }} --release
    - name: Test package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install daachorse --no-index --find-links target/wheels --force-reinstall
        mypy --strict tests
        pytest
    - name: Upload wheels
      uses: actions/upload-artifact@v7
      with:
        name: wheels-windows-${{ matrix.python-version }}-${{ matrix.target }}
        path: target/wheels

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14' ]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build package
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ matrix.target }}
        args: -i ${{ matrix.python-version }} --release --target universal2-apple-darwin
    - name: Test package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install daachorse --no-index --find-links target/wheels --force-reinstall
        mypy --strict tests
        pytest
    - name: Upload wheels
      uses: actions/upload-artifact@v7
      with:
        name: wheels-macos-${{ matrix.python-version }}
        path: target/wheels

  release:
    name: Release
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [ sdist, linux, musllinux, windows, macos ]
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          subject-path: 'wheels-*/*'
          merge-multiple: true
      - name: Install uv
        uses: astral-sh/setup-uv@v8
      - name: Publish to PyPI
        run: uv publish 'wheels-*/*'
