name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14' ]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build package
      uses: PyO3/maturin-action@v1
      with:
        manylinux: auto
        args: -i ${{ matrix.python-version }} --release
    - name: Test package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install daachorse --no-index --find-links target/wheels --force-reinstall
        mypy --strict tests
        pytest

  pack-sdist:
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Build package
      uses: PyO3/maturin-action@v1
      with:
        command: sdist
    - name: Upload wheels
      uses: actions/upload-artifact@v7
      with:
        name: wheels-sdist
        path: target/wheels

  pack-linux:
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [ test ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14' ]
        target: [ x86_64, i686 ]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build package
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ matrix.target }}
        manylinux: auto
        args: -i ${{ matrix.python-version }} --release
    - name: Upload wheels
      uses: actions/upload-artifact@v7
      with:
        name: wheels-linux-${{ matrix.python-version }}-${{ matrix.target }}
        path: target/wheels

  pack-windows:
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [ test ]
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14' ]
        target: [ x64, x86 ]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.target }}
    - name: Build package
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ matrix.target }}
        args: -i ${{ matrix.python-version }} --release
    - name: Upload wheels
      uses: actions/upload-artifact@v7
      with:
        name: wheels-windows-${{ matrix.python-version }}-${{ matrix.target }}
        path: target/wheels

  pack-macos:
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [ test ]
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14' ]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build package
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ matrix.target }}
        args: -i ${{ matrix.python-version }} --release --target universal2-apple-darwin
    - name: Upload wheels
      uses: actions/upload-artifact@v7
      with:
        name: wheels-macos-${{ matrix.python-version }}
        path: target/wheels

  release:
    name: Release
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [ pack-sdist, pack-linux, pack-windows, pack-macos ]
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: wheels-*
          merge-multiple: true
      - name: Install uv
        uses: astral-sh/setup-uv@v8
      - name: Publish to PyPI
        run: uv publish wheels-*/*
